name: loquate
version: 0.1.0.0
synopsis: Locale-Sensitive Pretty Printer
maintainer: Imuli <i@imu.li>
github: imuli/loquate
license: Unlicense
license-file: UNLICENSE
category: i18n
description: Provides types and type classes for generating locale specific pretty printed messages.

ghc-options: -Wall

dependencies:
  - array ^>= 0.5
  - base ^>= 4.13
  - data-default-class ^>= 0.1
  - prettyprinter ^>= 1.6
  - text ^>= 1.2

library:
  source-dirs: src
